export const searchNationality = (country: string) => {
  return getCountries().find(item => item.country === country)?.nationality || country
}

export const getCountries = () => {
  return [
    { nationality: 'AFGANA', country: 'AFGANISTÁN' },
    { nationality: 'ALBANESA', country: 'ALBANIA' },
    { nationality: 'ALEMANA', country: 'ALEMANIA' },
    { nationality: 'ALTO VOLTEÑA', country: 'ALTO VOLTA' },
    { nationality: 'ANDORRANA', country: 'ANDORRA' },
    { nationality: 'ANGOLEÑA', country: 'ANGOLA' },
    { nationality: 'ARGELINA', country: 'ARGELIA' },
    { nationality: 'ARGENTINA', country: 'ARGENTINA' },
    { nationality: 'AUSTRALIANA', country: 'AUSTRALIA' },
    { nationality: 'AUSTRIACA', country: 'AUSTRIA' },
    { nationality: 'BAHAMESA', country: 'BAHAMAS' },
    { nationality: 'BAHREINA', country: 'BAHREIN' },
    { nationality: 'BANGLADESHA', country: 'BANGLADESH' },
    { nationality: 'BARBADESA', country: 'BARBADOS' },
    { nationality: 'BELGA', country: 'BELGICA' },
    { nationality: 'BELICEÑA', country: 'BELICE' },
    { nationality: 'BERMUDESA', country: 'BERMUDAS' },
    { nationality: 'BIRMANA', country: 'BIRMANIA' },
    { nationality: 'BOLIVIANA', country: 'BOLIVIA' },
    { nationality: 'BOTSWANESA', country: 'BOTSWANA' },
    { nationality: 'BRASILEÑA', country: 'BRASIL' },
    { nationality: 'BULGARA', country: 'BULGARIA' },
    { nationality: 'BURUNDESA', country: 'BURUNDI' },
    { nationality: 'BUTANA', country: 'BUTAN' },
    { nationality: 'CAMBOYANA', country: 'KHEMER REP DE CAMBOYA ' },
    { nationality: 'CAMERUNESA', country: 'CAMERUN' },
    { nationality: 'CANADIENSE', country: 'CANADA' },
    { nationality: 'CENTROAFRICANA', country: 'REP CENTROAFRICANA' },
    { nationality: 'CHADEÑA', country: 'CHAD' },
    { nationality: 'CHECOSLOVACA', country: 'REP. CHECA' },
    { nationality: 'CHILENA', country: 'CHILE' },
    { nationality: 'CHINA', country: 'CHINA' },
    { nationality: 'CHINA', country: 'TAIWAN' },
    { nationality: 'CHIPRIOTA', country: 'CHIPRE' },
    { nationality: 'COLOMBIANA', country: 'COLOMBIA' },
    { nationality: 'CONGOLEÑA', country: 'CONGO' },
    { nationality: 'COSTARRICENSE', country: 'COSTA RICA' },
    { nationality: 'CUBANA', country: 'CUBA' },
    { nationality: 'DAHONEYA', country: 'DAHONEY' },
    { nationality: 'DANES', country: 'DINAMARCA' },
    { nationality: 'DOMINICANA', country: 'REP. DOMINICANA' },
    { nationality: 'ECUATORIANA', country: 'ECUADOR' },
    { nationality: 'EGIPCIA', country: 'EGIPTO' },
    { nationality: 'EMIRATA', country: 'EMIRATOS ARABES UDO.' },
    { nationality: 'ESCOSESA', country: 'ESCOCIA' },
    { nationality: 'ESLOVACA', country: 'REP. ESLOVACA' },
    { nationality: 'ESPAÑOLA', country: 'ESPAÑA' },
    { nationality: 'ESTONA', country: 'ESTONIA' },
    { nationality: 'ETIOPE', country: 'ETIOPIA' },
    { nationality: 'FIJENA', country: 'FIJI' },
    { nationality: 'FILIPINA', country: 'FILIPINAS' },
    { nationality: 'FINLANDESA', country: 'FINLANDIA' },
    { nationality: 'FRANCESA', country: 'FRANCIA' },
    { nationality: 'GABIANA', country: 'GAMBIA' },
    { nationality: 'GABONA', country: 'GABON' },
    { nationality: 'GALESA', country: 'GALES' },
    { nationality: 'GHANESA', country: 'GHANA' },
    { nationality: 'GRANADEÑA', country: 'GRANADA' },
    { nationality: 'GRIEGA', country: 'GRECIA' },
    { nationality: 'GUATEMALTECA', country: 'GUATEMALA' },
    { nationality: 'GUINESA ECUATORIANA', country: 'GUINEA ECUATORIAL' },
    { nationality: 'GUINESA', country: 'GUINEA' },
    { nationality: 'GUYANESA', country: 'GUYANA' },
    { nationality: 'HAITIANA', country: 'HAITI' },
    { nationality: 'HOLANDESA', country: 'HOLANDA' },
    { nationality: 'HONDUREÑA', country: 'HONDURAS' },
    { nationality: 'HUNGARA', country: 'HUNGRIA' },
    { nationality: 'INDIA', country: 'INDIA' },
    { nationality: 'INDONESA', country: 'INDONESIA' },
    { nationality: 'INGLESA', country: 'INGLATERRA' },
    { nationality: 'IRAKI', country: 'IRAK' },
    { nationality: 'IRANI', country: 'IRAN' },
    { nationality: 'IRLANDESA', country: 'IRLANDA' },
    { nationality: 'ISLANDESA', country: 'ISLANDIA' },
    { nationality: 'ISRAELI', country: 'ISRAEL' },
    { nationality: 'ITALIANA', country: 'ITALIA' },
    { nationality: 'JAMAIQUINA', country: 'JAMAICA' },
    { nationality: 'JAPONESA', country: 'JAPON' },
    { nationality: 'JORDANA', country: 'JORDANIA' },
    { nationality: 'KATENSA', country: 'KATAR' },
    { nationality: 'KENIANA', country: 'KENIA' },
    { nationality: 'KUWAITI', country: 'KWAIT' },
    { nationality: 'LAOSIANA', country: 'LAOS' },
    { nationality: 'LEONESA', country: 'SIERRA LEONA' },
    { nationality: 'LESOTHENSA', country: 'LESOTHO' },
    { nationality: 'LETONESA', country: 'LETONIA' },
    { nationality: 'LIBANESA', country: 'LIBANO' },
    { nationality: 'LIBERIANA', country: 'LIBERIA' },
    { nationality: 'LIBEÑA', country: 'LIBIA' },
    { nationality: 'LIECHTENSTEIN', country: 'LIECHTENSTEIN' },
    { nationality: 'LITUANA', country: 'LITUANIA' },
    { nationality: 'LUXEMBURGO', country: 'LUXEMBURGO' },
    { nationality: 'MADAGASCAR', country: 'MADAGASCAR' },
    { nationality: 'MALACA', country: 'FEDE. DE MALASIA' },
    { nationality: 'MALAWI', country: 'MALAWI' },
    { nationality: 'MALDIVAS', country: 'MALDIVAS' },
    { nationality: 'MALI', country: 'MALI' },
    { nationality: 'MALTESA', country: 'MALTA' },
    { nationality: 'MARFILESA', country: 'COSTA DE MARFIL' },
    { nationality: 'MARROQUI', country: 'MARRUECOS' },
    { nationality: 'MAURICIO', country: 'MAURICIO' },
    { nationality: 'MAURITANA', country: 'MAURITANIA' },
    { nationality: 'MEXICANA', country: 'MÉXICO' },
    { nationality: 'MONACO', country: 'MONACO' },
    { nationality: 'MONGOLESA', country: 'MONGOLIA' },
    { nationality: 'NAURU', country: 'NAURU' },
    { nationality: 'NEOZELANDESA', country: 'NUEVA ZELANDIA' },
    { nationality: 'NEPALESA', country: 'NEPAL' },
    { nationality: 'NICARAGUENSE', country: 'NICARAGUA' },
    { nationality: 'NIGERANA', country: 'NIGER' },
    { nationality: 'NIGERIANA', country: 'NIGERIA' },
    { nationality: 'NORCOREANA', country: 'COREA DEL NORTE' },
    { nationality: 'NORIRLANDESA', country: 'IRLANDA DEL NORTE' },
    { nationality: 'NORTEAMERICANA', country: 'ESTADOS UNIDOS' },
    { nationality: 'NORUEGA', country: 'NORUEGA' },
    { nationality: 'OMANA', country: 'OMAN' },
    { nationality: 'PAKISTANI', country: 'PAKISTAN' },
    { nationality: 'PANAMEÑA', country: 'PANAMA' },
    { nationality: 'PARAGUAYA', country: 'PARAGUAY' },
    { nationality: 'PERUANA', country: 'PERU' },
    { nationality: 'POLACA', country: 'POLONIA' },
    { nationality: 'PORTORIQUEÑA', country: 'PUERTO RICO' },
    { nationality: 'PORTUGUESA', country: 'PORTUGAL' },
    { nationality: 'RHODESIANA', country: 'RHODESIA' },
    { nationality: 'RUANDA', country: 'RUANDA' },
    { nationality: 'RUMANA', country: 'RUMANIA' },
    { nationality: 'RUSA', country: 'RUSSIA' },
    { nationality: 'SALVADOREÑA', country: 'EL SALVADOR' },
    { nationality: 'SAMOA OCCIDENTAL', country: 'SAMOA OCCIDENTAL' },
    { nationality: 'SAN MARINO', country: 'SAN MARINO' },
    { nationality: 'SAUDI', country: 'ARABIA SAUDITA' },
    { nationality: 'SENEGALESA', country: 'SENEGAL' },
    { nationality: 'SIKKIM', country: 'SIKKIM' },
    { nationality: 'SINGAPUR', country: 'SINGAPUR' },
    { nationality: 'SIRIA', country: 'SIRIA' },
    { nationality: 'SOMALIA', country: 'SOMALIA' },
    { nationality: 'SOVIETICA', country: 'UNION SOVIETICA' },
    { nationality: 'SRI LANKA', country: 'SRI LANKA (CEYLAN) ' },
    { nationality: 'SUAZILANDESA', country: 'SUAZILANDIA' },
    { nationality: 'SUDAFRICANA', country: 'SUDAFRICA' },
    { nationality: 'SUDANESA', country: 'SUDAN' },
    { nationality: 'SUECA', country: 'SUECIA' },
    { nationality: 'SUIZA', country: 'SUIZA' },
    { nationality: 'SURCOREANA', country: 'COREA DEL SUR' },
    { nationality: 'TAILANDESA', country: 'TAILANDIA' },
    { nationality: 'TANZANA', country: 'TANZANIA' },
    { nationality: 'TONGA', country: 'TONGA' },
    { nationality: 'TONGO', country: 'TONGO' },
    { nationality: 'TRINIDAD Y TOBAGO', country: 'TRINIDAD Y TOBAGO' },
    { nationality: 'TUNECINA', country: 'TUNEZ' },
    { nationality: 'TURCA', country: 'TURQUIA' },
    { nationality: 'UGANDESA', country: 'UGANDA' },
    { nationality: 'URUGUAYA', country: 'URUGUAY' },
    { nationality: 'VATICANO', country: 'VATICANO' },
    { nationality: 'VENEZOLANA', country: 'VENEZUELA' },
    { nationality: 'VIETNAMITA', country: 'VIETNAM' },
    { nationality: 'YEMEN REP ARABE', country: 'YEMEN REP. ARABE' },
    { nationality: 'YEMEN REP DEM', country: 'YEMEN REP. DEM' },
    { nationality: 'YUGOSLAVA', country: 'YUGOSLAVIA' },
    { nationality: 'ZAIRE', country: 'ZAIRE' }
  ]
}
